import type { GetStaticProps, NextPage } from "next";
import Head from "next/head";
import Image from "next/image";

import { RideMap, Streams } from "../libs/ride";

import "mapbox-gl/dist/mapbox-gl.css";
import styles from "../styles/Home.module.css";

import ride1 from "../data/netherlands/7648883160.json";
import ride2 from "../data/netherlands/7660086787.json";

interface Props {
  rides: Streams[];
}

const Home: NextPage<Props> = ({ rides }) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="#">Route Cleaner!</a>
        </h1>

        <div className={styles.grid}>
          <RideMap rides={rides} />
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export const getStaticProps: GetStaticProps = async () => {
  const rides = [ride1, ride2];
  return {
    props: {
      rides,
    },
  };
};

export default Home;
