import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { FC, useRef, useEffect } from "react";
import mapboxgl from "mapbox-gl";

import "mapbox-gl/dist/mapbox-gl.css";
import styles from "../styles/Home.module.css";

const MAPBOX_PUBLIC_KEY =
  "pk.eyJ1IjoibGx1biIsImEiOiJja2FqN2k2djIwNDU5MnlvNjR4YXRrMzFsIn0.Oir7SYHkVKBlgbPHldtRGQ";

const RideMap: FC = () => {
  const mapEl = useRef<HTMLDivElement>(null);
  mapboxgl.accessToken = MAPBOX_PUBLIC_KEY;

  useEffect(() => {
    const zoomLevel = (height?: number) => {
      switch (height) {
        case 250:
          return 6.8;
        case 400:
          return 7;
        default:
          return 7.25;
      }
    };

    new mapboxgl.Map({
      container: "map",
      style: "mapbox://styles/mapbox/light-v10",
      center: [4.902218907700037, 52.37208643243944],
      zoom: zoomLevel(mapEl?.current?.offsetHeight),
      minZoom: 6.8,
    });
  }, []);

  return <div ref={mapEl} id="map" className={styles.map} />;
};

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="#">Route Cleaner!</a>
        </h1>

        <RideMap />
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
